### ISSUE TITLE
Mod max heals token no matter what

### ISSUE THREAD

**Issue by Polygamoose** [tonifisler/foundry-token-health#17]
Until I last updated Foundry/this mod, it worked just fine. But since I updated both, this mod no longer works for me.
When I hit Enter or Shift Enter, the prompt comes up like normal. But no matter what I put in either prompt, the target's health raises to its maximum. Target has 1/100 health and I try to deal 1 damage? They're healed to 100. And if I try to heal them (shift enter) above their maximum, it does just that. Healing someone for 10 hp when they're 100/100 will make them 110/100.

Are there any known conflicts with other mods that would cause this mod to malfunction?

**Comment by jackkerouac** [comment]
Same for me. Module max heals regardless of what toggle key(s) you use.

**Comment by tonifisler** [comment]
Thanks for your report! it should be fixed in 0.2.2 which I just released 😉
