### ISSUE TITLE
Improvement to Escape behavior

### ISSUE THREAD

**Issue by apoapostolov** [tonifisler/foundry-token-health#2]
If user presses ESC while the focus is on the value field, close the window rather than just losing focus. Currently user must press ESC twice to close the window.

**Comment by tonifisler** [comment]
This is actually the exact behaviour intended by the "Fix ESC key" option from plutonium:

> Bind the "Escape" key to (in this order): de-select active input fields; de-select selected canvas elements; close context menus; close individual windows in most-recently-active-first order; toggle the main menu.

I have to make sure to override the same class function *after* plutonium. It seems hard to control the order in which all modules `Hooks.on('ready')` get fired 🤔

**Comment by Norc** [comment]
For what it's worth, in my latest test with foundry 0.5.5 and Token Health 0.1.5, pressing escape only once was needed to close the window.

**Comment by tonifisler** [comment]
Closing this, Giddy will improve ESC key handling in plutonium directly.
