### ISSUE TITLE
Numpad minus (-) key does not work in pop-up input field

### ISSUE THREAD

**Issue by kenster421** [tonifisler/foundry-token-health#5]
When adding health to tokens, the only way to do so is to use the number row minus key or by clicking the Heal button. The numpad minus key does not work.

**Comment by tonifisler** [comment]
Thanks for you report! 
I didn't experience that issue on my end. Could you provide some detail? Which system and modules are you using? Might be a conflict with another thing.

**Comment by kenster421** [comment]
Brand new world with only the Token Health module created. Game system: PF2e.
![image](https://user-images.githubusercontent.com/714257/80494072-3c3a9b80-8934-11ea-8092-d0fef1d09e92.png)

When applying healing using the minus key...

The numpad minus key does not work in the input field for health modification.
![image](https://user-images.githubusercontent.com/714257/80494624-db5f9300-8934-11ea-9733-d30d11fafebf.png)

Only the number row minus key works.
![image](https://user-images.githubusercontent.com/714257/80494731-00540600-8935-11ea-8ccd-bc3c04ef19dd.png)

**Comment by tonifisler** [comment]
Thank you for this clear explanation! 

I don't think it's something coming from the module though, as I never try to handle this key with a custom function. The input is a plain `type="number"` and it should work with any minus. Can the NumLock on your keyboard be interfering with this?

I sadly cannot test this right now, I'm doing everything from my laptop, without a numpad at hand. I'll try again as soon as I have access to one.

**Comment by kenster421** [comment]
You're very welcome!

I just tested this and NumLock On vs NumLock Off does not have any bearing on the ability to add a minus with the numpad minus key.

**Comment by tonifisler** [comment]
This helps! Thank you so much, I'll see if I can fix this then

**Comment by Norc** [comment]
For what it's worth, i couldn't reproduce this with Foundry 0.5.5 and Token Health 0.1.5, both minus keys were interpreted as negative values as expected for me..

**Comment by kenster421** [comment]
I'm going to close this issue, @tonifisler. Thank you, @Norc, for making me look further into this issue. It appears that my numpad minus key does not work in text inputs in Foundry at all when the game is launched. Before the game is launched, it works in the edit world screen just fine.

The numpad minus key does seem to work on the game screen to zoom out of the tabletop view.

I don't think this is a specific problem with my keyboard because the onscreen keyboard for windows shows the same behavior.

In any case, thanks for looking into this.

**Comment by tonifisler** [comment]
No problem! Maybe report this to Atropos as this issue might be caused by Foundry itself. 🤔

**Comment by kenster421** [comment]
A quick search of the Discord led me to a hotfix for 0.5.5 pinned in the beta temp discussion by Atropos. I regret that I didn't do this sooner. I applied the hotfix to my installation and everything is working fine now.

I like the change you made with the separate binding for health and keeping the old functionality of using negative values too.

**Comment by tonifisler** [comment]
No problem, I didn't remember that was something he was fixing in the hotfix.

Thank you so much! If you have any request or feedback, you're welcome to open other issues 😉
