### ISSUE TITLE
Feature request: Configurable keyboard shortcut

### ISSUE THREAD

**Issue by Norc** [tonifisler/foundry-token-health#8]
Sorry if there's a better way of doing this than a new issue.

Enter is great... except when I need it elsewhere. For example, when I manually override initiatives and hit Enter (5E, Combat Utility Belt Module), the health pops up which is mildly annoying.

**Comment by tonifisler** [comment]
Thank you for your report, can you make sure you are on the latest 0.1.5 version? This feature is already implemented 😉 

You should be able to reassign the key used to display the dialog from the module settings. 

However, the dialog showing when you are editing the initiative is a bug that should not happen. Can you tell me how to reproduce this exactly?

<img width="945" alt="Screenshot 2020-05-02 at 01 24 52" src="https://user-images.githubusercontent.com/1708450/80848757-a09b7a80-8c14-11ea-8d22-fbdf9f4fe3b6.png">

**Comment by Norc** [comment]
Yep, I was stuck on 0.1.2 (or earlier, before my latest update). Thanks for being way ahead of me!
