### ISSUE TITLE
Feature Request: Heal keyboard shortcut

### ISSUE THREAD

**Issue by Norc** [tonifisler/foundry-token-health#9]
When I have the Token Health interface open, and I enter a number, Enter applies the number as damage. I'd like to be able to press a different key (ideally for me, + on the numpad) to apply that number as healing instead.

**Comment by tonifisler** [comment]
This feature is already implemented in the latest 0.1.5 version. You should be able to set it in the module settings. Let me know if you can't do it, there might be some issues I didn't see.

 It is missing from the README file though and it should be there! I'll add it tomorrow.

Also, I noticed a translation string is missing thanks to your report.

**Comment by Norc** [comment]
Yes, this is working great in the latest version now that I see/have it. Perfect, thanks!
